Fixes this linker error:
libmultipartuploader.a(gsts3multipartuploader.cpp.obj) : error LNK2001: unresolved external symbol "struct _GstDebugCategory * gst_s3_sink_debug" (?gst_s3_sink_debug@@3PEAU_GstDebugCategory@@EA)
src/gsts3elements.dll : fatal error LNK1120: 1 unresolved externals

Essentially, the debug category is a C symbol, so put it inside
G_BEGIN_DECLS so that it doesn't get C++ symbol mangling.